/*
 *  © 2024 Peter Cole
 *
 *  This is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  It is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this code.  If not, see <https://www.gnu.org/licenses/>.
 */

/**
 * @file myConfig.example.h
 * @brief This is an example myConfig.h outlining the available options that can be set
 * @details
 * DO NOT EDIT THIS FILE! Copy it to myConfig.h and edit that.
 * Each available option is listed here with all commented out.
 * Uncomment and edit any options as required, noting you may not need to do this at all.
 * Default options are commented as such and will be used if you do not have a myConfig.h file.
 */

/**
 * @brief Options to define the log level which controls output to the EX-Display serial console.
 */
// #define LOG_LEVEL LOG_NONE     // Do not display any output
// #define LOG_LEVEL LOG_ERROR    // Display errors only
// #define LOG_LEVEL LOG_WARN     // Display warnings and errors (this is the default)
// #define LOG_LEVEL LOG_INFO     // Display information, warnings, and errors
// #define LOG_LEVEL LOG_DEBUG    // Display absolutely everything

/**
 * @brief Options to define which serial connections to use for the serial console and connecting to EX-CommandStation.
 */
// #define CONSOLE_STREAM Serial            // Serial console defaults to Serial (default on all platforms)
// #define COMMANDSTATION_STREAM Serial     // EX-CommandStation connected to Serial (default on Uno)
// #define COMMANDSTATION_STREAM Serial2    // EX-CommandStation connected to Serial2 (default on ESP32)
// #define COMMANDSTATION_STREAM Serial6    // EX-CommandStation connected to Serial6 (default on F411RE)

/**
 * @brief Option to change how long the EX-Display version is displayed, in milliseconds.
 */
// #define STARTUP_INFO_DELAY 3000    // default is 3 seconds/3000ms - Increase/decrease if desired

/**
 * @brief Option to force a touch screen to enter calibration mode even if the current calibration is valid
 */
// #define FORCE_CALIBRATION

/**
 * @brief Option provide an alternative option from the GFXFF FreeFonts that is not yet defined in the display type header file
 * e.g. set the text font to Free Sans Bold Oblique 18pt high. - uncomment the line below
 * which will replace the default definition or replace it with another.
 */

// #define TEXT_FONT &FreeSansBoldOblique18pt7b
